### ISSUE TITLE
Angular-Strap: Angular Bootstrap Wrapper (TODO)

### ISSUE THREAD

**Issue by respectYourNeighbour** [kosz/generator-modular#34]
When generating a project with angular-strap I've bumped into these 2 problems:
1. In app/app.js the controller should be named simple "main" and not "mainCtrl".
2. The generator didn't include bootstrap.css style automatically.

I fixed these 2 errors and it works smoothly now ;)

**Comment by kosz** [comment]
@respectYourNeighbour 

Thanks for your notes. I'd like to clarify these details a bit more : 
1. yes that one is due to indecision on what to call controllers and what names to use for controllerAs in general. I've fixed that particular error for now ( in the latest code base, but not inside release 0.3.0, as far as npm goes, this fix will be included in 0.4.0 sometimes this week ) , but I can't promise it won't happen again in the next minor releases, until the naming conventions and supporting code for them are in place 
2. Regarding the TODO choices from the generator. The choices listed as (TODO) are not implemented, however, the environment generated by the generator can be easily used to install those packages. 

You should not be adding the bootstrap.css manually. Instead, if you wish to use Angular-Strap, you should : 

2.1) generate a project by selecting ( 5. None ) 
2.2) Once the project is generated run the bower install for bootstrap and angular strap. Don't forget the --save flag, so that the build environment can know about these packages : 

```
bower install bootstrap --save
```

```
bower install angular-strap --save
```

By now if you're running gulp serve, your page should have reloaded and should include a bootstrap look and feel. But don't forget to : 
2.3) Import angular-strap into your angular app. You can do this by adding the dependency inside the module declaration in app.js : 

``` js
angular.module('respecttest', [
'ngRoute',
'mgcrea.ngStrap' // Angular-Strap module import 
])
```

Once these steps are done, you don't need to ( and you should not ) include the bootstrap.css manually in the app. Any external packages are managed automatically within the build system, by gulp and bower. 

If you have any trouble with these steps, please let me know, and I can share the project that I quickly created to produce these steps, as an example, or provide further assistance.

**Comment by respectYourNeighbour** [comment]
Thanks for the well documented answers, so far i really like the modular generator.
Success in further development!

**Comment by kosz** [comment]
Thanks respectYourNeighbour

Don't hesitate to ask any other questions you may have.
